GET http://localhost:8080/hotels

###

GET http://localhost:8080/hotels/1

###

DELETE http://localhost:8080/hotels/1

###

GET http://localhost:8080/hotels/1/rooms

###

GET http://localhost:8080/hotels/1/workers

###

PUT http://localhost:8080/hotels/1
Content-Type: application/json

{
  "id": 1,
  "chain_id": 1,
  "name": "Grand Hotel",
  "address": "123 Main St, Cityville",
  "country": "Countryland",
  "rooms": [
    {
      "id": 1,
      "number": 101,
      "price": 150,
      "booked": false
    },
    {
      "id": 2,
      "number": 102,
      "price": 200,
      "booked": true
    }
  ],
  "workers": [
    {
      "id": 1,
      "name": "John Epstein Doe",
      "age": 32,
      "position": "Manager"
    },
    {
      "id": 2,
      "name": "Jane Smith",
      "age": 28,
      "position": "Receptionist"
    }
  ]
}

### 

GET http://localhost:8080/chains/1/workers

###

GET http://localhost:8080/hotels/1/positions
